# Generated by Django 4.0.5 on 2022-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/pro'),
        ),
    ]
